.TH PASTA 1 2021-06-02
.SH NAME
pasta \- simple ssh pastebin client
.SH SYNOPSIS
.B pasta
[\fB-c\fR|\fB-g\fR|\fB-m\fR <url>|\fB\-p\fR] [\fB-x\fR] [\fBfilename\fR]
.SH DESCRIPTION
.B pasta
writes content provided over stdin to \fBfilename\fR on remote server via
pre-configured SSH connection.
.PP
If \fBfilename\fR was not provided, a random base64 string will be
used for the filename. If \fB-p\fR was given and \fBfilename\fR was not
\fB.png\fR will be appended to the random filename.
.SH OPTIONS
.TP
.BR \-c
Append to existing file (if it exists).
.TP
.BR \-g
Retrieve contents of file and write to stdout. Does not modify remote file.
.TP
.BR \-m\ <url>
Use curl(1) or wget(1) to upload contents of remote file from \fBurl\fR. Fetch
is done on SSH server to reduce network usage.
.TP
.BR \-p
Use import(1) command to take a selection-screenshot, and paste that instead
of reading stdin.
.TP
.BR \-x
Use xclip(1) to write remote filepath to clipboard.
.SH FILES
.TP 15
~/.config/pastarc
Application configuration file.
.SH EXAMPLE
Write 'Hello world' to a file called hello.txt
.PP
.nf
.RS
pasta hello.txt <<< 'Hello world'
.RE
.fi
.PP
Append 'Wow!' to hello.txt
.PP
.nf
.RS
pasta -c hello.txt <<< 'Wow!'
.RE
.fi
.PP
Upload a screenshot with a random filename and copy URL to X11 clipboard
.PP
.nf
.RS
pasta -xp
.RE
.fi
